# Generated by Django 2.1.4 on 2019-01-16 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('attribute_idx', models.IntegerField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('s_date', models.DateTimeField()),
                ('m_date', models.DateTimeField()),
                ('inode', models.CharField(max_length=100)),
                ('file_hash', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Attribute',
                'managed': False,
            },
        ),
    ]
