# Generated by Django 2.1.2 on 2018-12-14 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('issu_idx', models.AutoField(primary_key=True, serialize=False)),
                ('e_date', models.DateTimeField()),
                ('c_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'Certificate',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CertVf',
            fields=[
                ('cert_idx', models.AutoField(primary_key=True, serialize=False)),
                ('pre_hash', models.CharField(blank=True, max_length=100, null=True)),
                ('up_hash', models.CharField(blank=True, max_length=100, null=True)),
                ('c_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'Cert_vf',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('cont_idx', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('sort', models.CharField(max_length=100)),
                ('e_date', models.DateTimeField()),
                ('c_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'Contract',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DocVf',
            fields=[
                ('doc_idx', models.AutoField(primary_key=True, serialize=False)),
                ('pre_hash', models.CharField(blank=True, max_length=100, null=True)),
                ('up_hash', models.CharField(blank=True, max_length=100, null=True)),
                ('c_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'Doc_vf',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('file_idx', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.CharField(max_length=100)),
                ('file_name', models.CharField(max_length=100)),
                ('file_type', models.CharField(max_length=100)),
                ('file_hash', models.CharField(max_length=100)),
                ('s_date', models.DateTimeField()),
                ('c_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'File',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ItBoard',
            fields=[
                ('board_idx', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(blank=True, null=True)),
                ('count', models.IntegerField(blank=True, null=True)),
                ('c_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'It_board',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('notice_idx', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(blank=True, null=True)),
                ('count', models.IntegerField(blank=True, null=True)),
                ('c_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'Notice',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='test',
        ),
    ]
