# Generated by Django 2.1.4 on 2019-01-23 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groot', '0002_attribute'),
    ]

    operations = [
        migrations.CreateModel(
            name='Similarity',
            fields=[
                ('similarity_idx', models.IntegerField(primary_key=True, serialize=False)),
                ('summary_value', models.CharField(blank=True, max_length=100, null=True)),
                ('keyword_value', models.CharField(blank=True, max_length=100, null=True)),
                ('result', models.CharField(blank=True, max_length=100, null=True)),
                ('c_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'Similarity',
                'managed': False,
            },
        ),
    ]
