# Generated by Django 2.1.4 on 2019-01-28 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groot', '0003_similarity'),
        ('groot', '0004_expire_extend_update'),
    ]

    operations = [
    ]
